[[main]]
  name = "À propos"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projets"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Démos"
  pageRef = "zero-time-demos"
  weight = 30

[[main]]
  name = "Bizarreries"
  pageRef = "quirks"
  weight = 40

[[main]]
  name = "GitHub"
  identifier = "github"
  pre = "github"
  url = "https://github.com/gustaveWPM"
  weight = 400

[[footer]]
  name = "Catégories"
  pageRef = "topics"
  weight = 10
